// src/auth/permissions.enum.ts
export enum Permission {
    CREATE_INDIVIDUAL_KPI = "CREATE_INDIVIDUAL_KPI",
    VIEW_INDIVIDUAL_KPI = "VIEW_INDIVIDUAL_KPI",
    EDIT_INDIVIDUAL_KPI = "EDIT_INDIVIDUAL_KPI",
    CREATE_TEAM_KPI = "CREATE_TEAM_KPI",
    VIEW_TEAM_KPI = "VIEW_TEAM_KPI",
    EDIT_TEAM_KPI = "EDIT_TEAM_KPI",
    CREATE_ALL_KPI = "CREATE_ALL_KPI",
    VIEW_ALL_KPI = "VIEW_ALL_KPI",
    EDIT_ALL_KPI = "EDIT_ALL_KPI",
  

    // Priority permissions
  CREATE_INDIVIDUAL_PRIORITY = "CREATE_INDIVIDUAL_PRIORITY",
  VIEW_INDIVIDUAL_PRIORITY = "VIEW_INDIVIDUAL_PRIORITY",
  EDIT_INDIVIDUAL_PRIORITY = "EDIT_INDIVIDUAL_PRIORITY",
  CREATE_TEAM_PRIORITY = "CREATE_TEAM_PRIORITY",
  VIEW_TEAM_PRIORITY = "VIEW_TEAM_PRIORITY",
  EDIT_TEAM_PRIORITY = "EDIT_TEAM_PRIORITY",
  CREATE_ALL_PRIORITY = "CREATE_ALL_PRIORITY",
  VIEW_ALL_PRIORITY = "VIEW_ALL_PRIORITY",
  EDIT_ALL_PRIORITY = "EDIT_ALL_PRIORITY",

    VIEW_INDIVIDUAL_DASHBOARD = "VIEW_INDIVIDUAL_DASHBOARD",
    VIEW_TEAM_DASHBOARD = "VIEW_TEAM_DASHBOARD",
    VIEW_COMPANY_DASHBOARD = "VIEW_COMPANY_DASHBOARD",
  
    VIEW_USERS = "VIEW_USERS",
    MANAGE_USERS = "MANAGE_USERS",
  
    VIEW_TEAMS = "VIEW_TEAMS",
    MANAGE_TEAMS = "MANAGE_TEAMS",
  
    MANAGE_CONFIGURATION = "MANAGE_CONFIGURATION",
  }
  
  export enum Role {
    USER = "user",
    MANAGER = "manager",
    ADMIN = "admin",
    ORGANIZATION_OWNER = "organization_owner",
  }
  