// src/auth/role-permission-mapping.ts
import { Permission, Role } from './permissions.enum';

export const rolePermissions: Record<Role, Permission[]> = {
  [Role.USER]: [
    Permission.VIEW_INDIVIDUAL_KPI,
    Permission.EDIT_INDIVIDUAL_KPI,
    Permission.CREATE_INDIVIDUAL_KPI,
    Permission.VIEW_TEAM_KPI,
    Permission.VIEW_INDIVIDUAL_DASHBOARD,
    Permission.VIEW_TEAM_DASHBOARD,
    Permission.VIEW_COMPANY_DASHBOARD,
    Permission.VIEW_USERS,
    Permission.VIEW_TEAMS,

     // Priority permissions for USER
       Permission.CREATE_INDIVIDUAL_PRIORITY,
    Permission.VIEW_INDIVIDUAL_PRIORITY,
    Permission.EDIT_INDIVIDUAL_PRIORITY,
    Permission.VIEW_TEAM_PRIORITY,
  ],
  [Role.MANAGER]: [
    Permission.CREATE_INDIVIDUAL_KPI,
    Permission.VIEW_INDIVIDUAL_KPI,
    Permission.EDIT_INDIVIDUAL_KPI,
    Permission.CREATE_TEAM_KPI,
    Permission.VIEW_TEAM_KPI,
    Permission.EDIT_TEAM_KPI,
    Permission.VIEW_INDIVIDUAL_DASHBOARD,
    Permission.VIEW_TEAM_DASHBOARD,
    Permission.VIEW_COMPANY_DASHBOARD,
    Permission.VIEW_TEAM_KPI,
    Permission.EDIT_TEAM_KPI,
    Permission.VIEW_TEAMS,
    Permission.MANAGE_TEAMS,
    Permission.VIEW_USERS,
    Permission.MANAGE_USERS,

     // Priority permissions for MANAGER
    Permission.CREATE_INDIVIDUAL_PRIORITY,
    Permission.VIEW_INDIVIDUAL_PRIORITY,
    Permission.EDIT_INDIVIDUAL_PRIORITY,
    Permission.CREATE_TEAM_PRIORITY,
    Permission.VIEW_TEAM_PRIORITY,
    Permission.EDIT_TEAM_PRIORITY,
    // Permission.VIEW_ALL_PRIORITY,
  ],
  [Role.ADMIN]: [
    Permission.CREATE_INDIVIDUAL_KPI,
    Permission.CREATE_TEAM_KPI,
    Permission.CREATE_ALL_KPI,
    Permission.VIEW_INDIVIDUAL_KPI,
    Permission.VIEW_TEAM_KPI,
    Permission.VIEW_ALL_KPI,
    Permission.EDIT_INDIVIDUAL_KPI,
    Permission.EDIT_TEAM_KPI,
    Permission.EDIT_ALL_KPI,
    Permission.VIEW_INDIVIDUAL_DASHBOARD,
    Permission.VIEW_TEAM_DASHBOARD,
    Permission.VIEW_COMPANY_DASHBOARD,
    Permission.VIEW_USERS,
    Permission.MANAGE_USERS,
    Permission.VIEW_TEAMS,
    Permission.MANAGE_TEAMS,
    Permission.MANAGE_CONFIGURATION,
    // Priority permissions for ADMIN
    Permission.CREATE_ALL_PRIORITY,
    Permission.CREATE_INDIVIDUAL_PRIORITY,
    Permission.CREATE_TEAM_PRIORITY,
    Permission.VIEW_INDIVIDUAL_PRIORITY,
    Permission.VIEW_ALL_PRIORITY,
    Permission.VIEW_TEAM_PRIORITY,
    Permission.EDIT_ALL_PRIORITY,
    Permission.EDIT_INDIVIDUAL_PRIORITY,
    Permission.EDIT_TEAM_PRIORITY,
  ],
  [Role.ORGANIZATION_OWNER]: [
    Permission.CREATE_INDIVIDUAL_KPI,
    Permission.CREATE_ALL_KPI,
    Permission.CREATE_TEAM_KPI,
    Permission.VIEW_INDIVIDUAL_KPI,
    Permission.VIEW_TEAM_KPI,
    Permission.VIEW_ALL_KPI,
    Permission.EDIT_INDIVIDUAL_KPI,
    Permission.EDIT_TEAM_KPI,
    Permission.EDIT_ALL_KPI,
    Permission.VIEW_INDIVIDUAL_DASHBOARD,
    Permission.VIEW_TEAM_DASHBOARD,
    Permission.VIEW_COMPANY_DASHBOARD,
    Permission.VIEW_USERS,
    Permission.MANAGE_USERS,
    Permission.VIEW_TEAMS,
    Permission.MANAGE_TEAMS,
    Permission.MANAGE_CONFIGURATION,
    // Priority permissions for ADMIN
    Permission.CREATE_ALL_PRIORITY,
    Permission.CREATE_INDIVIDUAL_PRIORITY,
    Permission.CREATE_TEAM_PRIORITY,
    Permission.VIEW_INDIVIDUAL_PRIORITY,
    Permission.VIEW_ALL_PRIORITY,
    Permission.VIEW_TEAM_PRIORITY,
    Permission.EDIT_ALL_PRIORITY,
    Permission.EDIT_INDIVIDUAL_PRIORITY,
    Permission.EDIT_TEAM_PRIORITY,
  ],
};
